// Code generated by protoc-gen-gin with resty client. DO NOT EDIT.
// versions:
// - protoc-gen-gin v1.0.0
// - protoc             v3.12.4
// source: complete_example.proto

package api

import (
	context "context"
	fmt "fmt"
	gin "github.com/gin-gonic/gin"
	binding "github.com/gin-gonic/gin/binding"
	binding1 "github.com/go-kenka/ginpb/binding"
	client "github.com/go-kenka/ginpb/client"
	metadata "github.com/go-kenka/ginpb/metadata"
	middleware "github.com/go-kenka/ginpb/middleware"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the resty client it is being compiled against.
var _ = new(context.Context)
var _ = new(metadata.GinData)
var _ = new(gin.H)
var _ = new(client.Client)
var _ = binding.JSON
var _ = binding1.BindByContentType
var _ = middleware.Chain
var _ = fmt.Sprintf
var _ = strings.ReplaceAll

const OperationCompleteExampleServiceBatchDeleteUsers = "/example.CompleteExampleService/BatchDeleteUsers"
const OperationCompleteExampleServiceCreatePost = "/example.CompleteExampleService/CreatePost"
const OperationCompleteExampleServiceCreateUser = "/example.CompleteExampleService/CreateUser"
const OperationCompleteExampleServiceDeleteUser = "/example.CompleteExampleService/DeleteUser"
const OperationCompleteExampleServiceGetPostComments = "/example.CompleteExampleService/GetPostComments"
const OperationCompleteExampleServiceGetUser = "/example.CompleteExampleService/GetUser"
const OperationCompleteExampleServiceGetUserProfile = "/example.CompleteExampleService/GetUserProfile"
const OperationCompleteExampleServiceListUsers = "/example.CompleteExampleService/ListUsers"
const OperationCompleteExampleServicePatchUser = "/example.CompleteExampleService/PatchUser"
const OperationCompleteExampleServiceRegisterUser = "/example.CompleteExampleService/RegisterUser"
const OperationCompleteExampleServiceSearchUsers = "/example.CompleteExampleService/SearchUsers"
const OperationCompleteExampleServiceUpdateProfile = "/example.CompleteExampleService/UpdateProfile"
const OperationCompleteExampleServiceUpdateUser = "/example.CompleteExampleService/UpdateUser"

type CompleteExampleServiceHTTPServer interface {
	BatchDeleteUsers(context.Context, *BatchDeleteUsersRequest) (*BatchDeleteUsersResponse, error)
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GetPostComments(context.Context, *GetPostCommentsRequest) (*GetPostCommentsResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	PatchUser(context.Context, *PatchUserRequest) (*PatchUserResponse, error)
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
}

// RegisterOption defines registration options
type CompleteExampleServiceRegisterOption func(*CompleteExampleServiceRegisterOptions)

// CompleteExampleServiceRegisterOptions registration configuration options
type CompleteExampleServiceRegisterOptions struct {
	globalMiddlewares    []gin.HandlerFunc
	operationMiddlewares map[string][]gin.HandlerFunc
}

// WithGlobalMiddleware adds global middleware
func WithCompleteExampleServiceGlobalMiddleware(middlewares ...gin.HandlerFunc) CompleteExampleServiceRegisterOption {
	return func(o *CompleteExampleServiceRegisterOptions) {
		o.globalMiddlewares = append(o.globalMiddlewares, middlewares...)
	}
}

// WithOperationMiddleware adds middleware for specific operation
func WithCompleteExampleServiceOperationMiddleware(operation string, middlewares ...gin.HandlerFunc) CompleteExampleServiceRegisterOption {
	return func(o *CompleteExampleServiceRegisterOptions) {
		if o.operationMiddlewares == nil {
			o.operationMiddlewares = make(map[string][]gin.HandlerFunc)
		}
		o.operationMiddlewares[operation] = append(o.operationMiddlewares[operation], middlewares...)
	}
}

// WithOperationMiddlewares sets middleware for multiple operations
func WithCompleteExampleServiceOperationMiddlewares(middlewares map[string][]gin.HandlerFunc) CompleteExampleServiceRegisterOption {
	return func(o *CompleteExampleServiceRegisterOptions) {
		if o.operationMiddlewares == nil {
			o.operationMiddlewares = make(map[string][]gin.HandlerFunc)
		}
		for operation, mws := range middlewares {
			o.operationMiddlewares[operation] = append(o.operationMiddlewares[operation], mws...)
		}
	}
}

// RegisterCompleteExampleServiceHTTPServer registers HTTP server with function options pattern
func RegisterCompleteExampleServiceHTTPServer(r gin.IRouter, srv CompleteExampleServiceHTTPServer, opts ...CompleteExampleServiceRegisterOption) {
	options := &CompleteExampleServiceRegisterOptions{}
	for _, opt := range opts {
		opt(options)
	}

	// Helper function to register route with middleware support
	registerRoute := func(method, path, operation string, handler gin.HandlerFunc) {
		var finalHandlers []gin.HandlerFunc

		// Add global middlewares first
		finalHandlers = append(finalHandlers, options.globalMiddlewares...)

		// Add operation-specific middlewares
		if operationMws, exists := options.operationMiddlewares[operation]; exists {
			finalHandlers = append(finalHandlers, operationMws...)
		}

		// Add the handler at the end
		finalHandlers = append(finalHandlers, handler)

		// Register the route
		r.Handle(method, path, finalHandlers...)
	}
	registerRoute("GET", "/api/v1/users", OperationCompleteExampleServiceListUsers, _CompleteExampleService_ListUsers0_HTTP_Handler(srv))
	registerRoute("GET", "/api/v1/users/:user_id", OperationCompleteExampleServiceGetUser, _CompleteExampleService_GetUser0_HTTP_Handler(srv))
	registerRoute("GET", "/api/v1/users/search", OperationCompleteExampleServiceSearchUsers, _CompleteExampleService_SearchUsers0_HTTP_Handler(srv))
	registerRoute("POST", "/api/v1/users", OperationCompleteExampleServiceCreateUser, _CompleteExampleService_CreateUser0_HTTP_Handler(srv))
	registerRoute("POST", "/api/v1/users/register", OperationCompleteExampleServiceRegisterUser, _CompleteExampleService_RegisterUser0_HTTP_Handler(srv))
	registerRoute("POST", "/api/v1/users/:user_id/posts", OperationCompleteExampleServiceCreatePost, _CompleteExampleService_CreatePost0_HTTP_Handler(srv))
	registerRoute("PUT", "/api/v1/users/:user_id", OperationCompleteExampleServiceUpdateUser, _CompleteExampleService_UpdateUser0_HTTP_Handler(srv))
	registerRoute("PUT", "/api/v1/users/:user_id/profile", OperationCompleteExampleServiceUpdateProfile, _CompleteExampleService_UpdateProfile0_HTTP_Handler(srv))
	registerRoute("PATCH", "/api/v1/users/:user_id", OperationCompleteExampleServicePatchUser, _CompleteExampleService_PatchUser0_HTTP_Handler(srv))
	registerRoute("DELETE", "/api/v1/users/:user_id", OperationCompleteExampleServiceDeleteUser, _CompleteExampleService_DeleteUser0_HTTP_Handler(srv))
	registerRoute("DELETE", "/api/v1/users", OperationCompleteExampleServiceBatchDeleteUsers, _CompleteExampleService_BatchDeleteUsers0_HTTP_Handler(srv))
	registerRoute("GET", "/api/v1/users/:user_id/posts/:post_id/comments", OperationCompleteExampleServiceGetPostComments, _CompleteExampleService_GetPostComments0_HTTP_Handler(srv))
	registerRoute("GET", "/api/v1/profiles/:user_id", OperationCompleteExampleServiceGetUserProfile, _CompleteExampleService_GetUserProfile0_HTTP_Handler(srv))
	registerRoute("GET", "/api/v1/users/:user_id/profile", OperationCompleteExampleServiceGetUserProfile, _CompleteExampleService_GetUserProfile1_HTTP_Handler(srv))
}

func _CompleteExampleService_ListUsers0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceListUsers)

		var ginReq _ListUsersGinRequest
		// query
		if err := ctx.BindQuery(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toListUsersRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.ListUsers(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_GetUser0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceGetUser)

		var ginReq _GetUserGinRequest
		// query
		if err := ctx.BindQuery(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// params
		if err := ctx.BindUri(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toGetUserRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.GetUser(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_SearchUsers0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceSearchUsers)

		var ginReq _SearchUsersGinRequest
		// query
		if err := ctx.BindQuery(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toSearchUsersRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.SearchUsers(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_CreateUser0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceCreateUser)

		var ginReq _CreateUserGinRequest
		// body binding with automatic Content-Type detection
		if err := binding1.BindByContentType(ctx, &ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toCreateUserRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.CreateUser(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_RegisterUser0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceRegisterUser)

		var ginReq _RegisterUserGinRequest
		// body binding with automatic Content-Type detection
		if err := binding1.BindByContentType(ctx, &ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toRegisterUserRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.RegisterUser(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_CreatePost0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceCreatePost)

		var ginReq _CreatePostGinRequest
		// body binding with automatic Content-Type detection
		if err := binding1.BindByContentType(ctx, &ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// params
		if err := ctx.BindUri(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toCreatePostRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.CreatePost(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_UpdateUser0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceUpdateUser)

		var ginReq _UpdateUserGinRequest
		// body binding with automatic Content-Type detection
		if err := binding1.BindByContentType(ctx, &ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// params
		if err := ctx.BindUri(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toUpdateUserRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.UpdateUser(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_UpdateProfile0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceUpdateProfile)

		var ginReq _UpdateProfileGinRequest
		// body binding with automatic Content-Type detection
		if err := binding1.BindByContentType(ctx, &ginReq); err != nil {
			ctx.Error(err)
			return
		}
		// query
		if err := ctx.BindQuery(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// params
		if err := ctx.BindUri(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toUpdateProfileRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.UpdateProfile(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_PatchUser0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServicePatchUser)

		var ginReq _PatchUserGinRequest
		// body binding with automatic Content-Type detection
		if err := binding1.BindByContentType(ctx, &ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// params
		if err := ctx.BindUri(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toPatchUserRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.PatchUser(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_DeleteUser0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceDeleteUser)

		var ginReq _DeleteUserGinRequest
		// query
		if err := ctx.BindQuery(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// params
		if err := ctx.BindUri(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toDeleteUserRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.DeleteUser(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_BatchDeleteUsers0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceBatchDeleteUsers)

		var ginReq _BatchDeleteUsersGinRequest
		// query
		if err := ctx.BindQuery(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toBatchDeleteUsersRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.BatchDeleteUsers(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_GetPostComments0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceGetPostComments)

		var ginReq _GetPostCommentsGinRequest
		// query
		if err := ctx.BindQuery(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// params
		if err := ctx.BindUri(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toGetPostCommentsRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.GetPostComments(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_GetUserProfile0_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceGetUserProfile)

		var ginReq _GetUserProfileGinRequest
		// query
		if err := ctx.BindQuery(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// params
		if err := ctx.BindUri(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toGetUserProfileRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.GetUserProfile(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

func _CompleteExampleService_GetUserProfile1_HTTP_Handler(srv CompleteExampleServiceHTTPServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		// Set operation for middleware
		ctx.Set("operation", OperationCompleteExampleServiceGetUserProfile)

		var ginReq _GetUserProfileGinRequest
		// query
		if err := ctx.BindQuery(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// params
		if err := ctx.BindUri(&ginReq); err != nil {
			ctx.Error(err)
			return
		}

		// Convert gin request to protobuf request
		in := ginReq.toGetUserProfileRequest()

		// Use new context for metadata passing, including request, writer and route params
		newCtx := metadata.NewContext(ctx)
		reply, err := srv.GetUserProfile(newCtx, in)
		if err != nil {
			ctx.Error(err)
			return
		}
		ctx.JSON(200, reply)
	}
}

type CompleteExampleServiceHTTPClient interface {
	BatchDeleteUsers(ctx context.Context, req *BatchDeleteUsersRequest, opts ...client.CallOption) (rsp *BatchDeleteUsersResponse, err error)
	CreatePost(ctx context.Context, req *CreatePostRequest, opts ...client.CallOption) (rsp *CreatePostResponse, err error)
	CreateUser(ctx context.Context, req *CreateUserRequest, opts ...client.CallOption) (rsp *CreateUserResponse, err error)
	DeleteUser(ctx context.Context, req *DeleteUserRequest, opts ...client.CallOption) (rsp *DeleteUserResponse, err error)
	GetPostComments(ctx context.Context, req *GetPostCommentsRequest, opts ...client.CallOption) (rsp *GetPostCommentsResponse, err error)
	GetUser(ctx context.Context, req *GetUserRequest, opts ...client.CallOption) (rsp *GetUserResponse, err error)
	GetUserProfile(ctx context.Context, req *GetUserProfileRequest, opts ...client.CallOption) (rsp *GetUserProfileResponse, err error)
	ListUsers(ctx context.Context, req *ListUsersRequest, opts ...client.CallOption) (rsp *ListUsersResponse, err error)
	PatchUser(ctx context.Context, req *PatchUserRequest, opts ...client.CallOption) (rsp *PatchUserResponse, err error)
	RegisterUser(ctx context.Context, req *RegisterUserRequest, opts ...client.CallOption) (rsp *RegisterUserResponse, err error)
	SearchUsers(ctx context.Context, req *SearchUsersRequest, opts ...client.CallOption) (rsp *SearchUsersResponse, err error)
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest, opts ...client.CallOption) (rsp *UpdateProfileResponse, err error)
	UpdateUser(ctx context.Context, req *UpdateUserRequest, opts ...client.CallOption) (rsp *UpdateUserResponse, err error)
}

type CompleteExampleServiceHTTPClientImpl struct {
	client client.Client
}

func NewCompleteExampleServiceHTTPClient(opts ...client.ClientOption) CompleteExampleServiceHTTPClient {
	c := client.NewClient(opts...)
	return &CompleteExampleServiceHTTPClientImpl{client: c}
}

func (c *CompleteExampleServiceHTTPClientImpl) BatchDeleteUsers(ctx context.Context, in *BatchDeleteUsersRequest, opts ...client.CallOption) (*BatchDeleteUsersResponse, error) {
	var out BatchDeleteUsersResponse

	// Build request path
	path := "/api/v1/users"
	// DELETE request
	err := c.client.Invoke(ctx, "DELETE", path, nil, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("DELETE /api/v1/users failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...client.CallOption) (*CreatePostResponse, error) {
	var out CreatePostResponse

	// Build request path
	path := "/api/v1/users/{user_id}/posts"
	// Replace path parameters
	path = strings.ReplaceAll(path, "{user_id}", fmt.Sprintf("%v", in.UserId))
	// POST request
	err := c.client.Invoke(ctx, "POST", path, in, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("POST /api/v1/users/{user_id}/posts failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...client.CallOption) (*CreateUserResponse, error) {
	var out CreateUserResponse

	// Build request path
	path := "/api/v1/users"
	// POST request
	err := c.client.Invoke(ctx, "POST", path, in, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("POST /api/v1/users failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...client.CallOption) (*DeleteUserResponse, error) {
	var out DeleteUserResponse

	// Build request path
	path := "/api/v1/users/{user_id}"
	// Replace path parameters
	path = strings.ReplaceAll(path, "{user_id}", fmt.Sprintf("%v", in.UserId))
	// DELETE request
	err := c.client.Invoke(ctx, "DELETE", path, nil, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("DELETE /api/v1/users/{user_id} failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) GetPostComments(ctx context.Context, in *GetPostCommentsRequest, opts ...client.CallOption) (*GetPostCommentsResponse, error) {
	var out GetPostCommentsResponse

	// Build request path
	path := "/api/v1/users/{user_id}/posts/{post_id}/comments"
	// Replace path parameters
	path = strings.ReplaceAll(path, "{user_id}", fmt.Sprintf("%v", in.UserId))
	path = strings.ReplaceAll(path, "{post_id}", fmt.Sprintf("%v", in.PostId))
	// GET request
	err := c.client.Invoke(ctx, "GET", path, nil, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("GET /api/v1/users/{user_id}/posts/{post_id}/comments failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) GetUser(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error) {
	var out GetUserResponse

	// Build request path
	path := "/api/v1/users/{user_id}"
	// Replace path parameters
	path = strings.ReplaceAll(path, "{user_id}", fmt.Sprintf("%v", in.UserId))
	// GET request
	err := c.client.Invoke(ctx, "GET", path, nil, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("GET /api/v1/users/{user_id} failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...client.CallOption) (*GetUserProfileResponse, error) {
	var out GetUserProfileResponse

	// Build request path
	path := "/api/v1/users/{user_id}/profile"
	// Replace path parameters
	path = strings.ReplaceAll(path, "{user_id}", fmt.Sprintf("%v", in.UserId))
	// GET request
	err := c.client.Invoke(ctx, "GET", path, nil, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("GET /api/v1/users/{user_id}/profile failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...client.CallOption) (*ListUsersResponse, error) {
	var out ListUsersResponse

	// Build request path
	path := "/api/v1/users"
	// GET request
	err := c.client.Invoke(ctx, "GET", path, nil, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("GET /api/v1/users failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) PatchUser(ctx context.Context, in *PatchUserRequest, opts ...client.CallOption) (*PatchUserResponse, error) {
	var out PatchUserResponse

	// Build request path
	path := "/api/v1/users/{user_id}"
	// Replace path parameters
	path = strings.ReplaceAll(path, "{user_id}", fmt.Sprintf("%v", in.UserId))
	// PATCH request
	err := c.client.Invoke(ctx, "PATCH", path, in, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("PATCH /api/v1/users/{user_id} failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...client.CallOption) (*RegisterUserResponse, error) {
	var out RegisterUserResponse

	// Build request path
	path := "/api/v1/users/register"
	// POST request
	err := c.client.Invoke(ctx, "POST", path, in, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("POST /api/v1/users/register failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...client.CallOption) (*SearchUsersResponse, error) {
	var out SearchUsersResponse

	// Build request path
	path := "/api/v1/users/search"
	// GET request
	err := c.client.Invoke(ctx, "GET", path, nil, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("GET /api/v1/users/search failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...client.CallOption) (*UpdateProfileResponse, error) {
	var out UpdateProfileResponse

	// Build request path
	path := "/api/v1/users/{user_id}/profile"
	// Replace path parameters
	path = strings.ReplaceAll(path, "{user_id}", fmt.Sprintf("%v", in.UserId))
	// PUT request
	err := c.client.Invoke(ctx, "PUT", path, in.Profile, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("PUT /api/v1/users/{user_id}/profile failed: %w", err)
	}
	return &out, nil
}

func (c *CompleteExampleServiceHTTPClientImpl) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...client.CallOption) (*UpdateUserResponse, error) {
	var out UpdateUserResponse

	// Build request path
	path := "/api/v1/users/{user_id}"
	// Replace path parameters
	path = strings.ReplaceAll(path, "{user_id}", fmt.Sprintf("%v", in.UserId))
	// PUT request
	err := c.client.Invoke(ctx, "PUT", path, in, &out, opts...)

	if err != nil {
		return nil, fmt.Errorf("PUT /api/v1/users/{user_id} failed: %w", err)
	}
	return &out, nil
}

// Internal structs with gin binding tags for protobuf messages

// _BatchDeleteUsersGinRequest provides gin binding tags for BatchDeleteUsersRequest
type _BatchDeleteUsersGinRequest struct {
	UserIds           []string `json:"user_ids" form:"user_ids" binding:"required,min=1,max=100"`
	HardDelete        bool     `json:"hard_delete" form:"hard_delete"`
	DeleteReason      string   `json:"delete_reason" form:"reason"`
	BatchConfirmation string   `json:"batch_confirmation" header:"X-Batch-Confirm" binding:"required"`
	Authorization     string   `json:"authorization" header:"Authorization" binding:"required"`
	OperationId       string   `json:"operation_id" header:"X-Operation-ID"`
}

// convertBatchDeleteUsersGinRequest converts from gin request struct to protobuf struct
func (r *_BatchDeleteUsersGinRequest) toBatchDeleteUsersRequest() *BatchDeleteUsersRequest {
	return &BatchDeleteUsersRequest{
		UserIds:           r.UserIds,
		HardDelete:        r.HardDelete,
		DeleteReason:      r.DeleteReason,
		BatchConfirmation: r.BatchConfirmation,
		Authorization:     r.Authorization,
		OperationId:       r.OperationId,
	}
}

// _CreatePostGinRequest provides gin binding tags for CreatePostRequest
type _CreatePostGinRequest struct {
	UserId          string            `json:"user_id" uri:"user_id" binding:"required,uuid"`
	Draft           bool              `json:"draft" form:"draft"`
	Source          string            `json:"source" form:"source" binding:"oneof=web mobile app api"`
	NotifyFollowers bool              `json:"notify_followers" form:"notify_followers"`
	Authorization   string            `json:"authorization" header:"Authorization" binding:"required,startswith=Bearer "`
	ContentType     string            `json:"content_type" header:"Content-Type" binding:"required"`
	UserAgent       string            `json:"user_agent" header:"User-Agent"`
	ClientVersion   string            `json:"client_version" header:"X-Client-Version"`
	RequestId       string            `json:"request_id" header:"X-Request-ID"`
	Title           string            `json:"title" binding:"required,min=5,max=200"`
	Content         string            `json:"content" binding:"required,min=50,max=50000"`
	Excerpt         string            `json:"excerpt" binding:"max=500"`
	Category        string            `json:"category" binding:"required"`
	Tags            []string          `json:"tags" binding:"min=1,max=10"`
	Visibility      string            `json:"visibility" binding:"required,oneof=public private draft"`
	AllowComments   bool              `json:"allow_comments"`
	PublishAt       string            `json:"publish_at" binding:"datetime=2006-01-02T15:04:05Z07:00"`
	MetaTitle       string            `json:"meta_title" binding:"max=60"`
	MetaDescription string            `json:"meta_description" binding:"max=160"`
	SeoKeywords     []string          `json:"seo_keywords" binding:"max=10"`
	ImageUrls       []string          `json:"images" binding:"max=20"`
	AttachmentUrls  []string          `json:"attachments" binding:"max=10"`
	CustomFields    map[string]string `json:"custom_fields" xml:"validate:post_custom_fields"`
	ExternalId      string            `json:"external_id" xml:"external_id_format"`
}

// convertCreatePostGinRequest converts from gin request struct to protobuf struct
func (r *_CreatePostGinRequest) toCreatePostRequest() *CreatePostRequest {
	return &CreatePostRequest{
		UserId:          r.UserId,
		Draft:           r.Draft,
		Source:          r.Source,
		NotifyFollowers: r.NotifyFollowers,
		Authorization:   r.Authorization,
		ContentType:     r.ContentType,
		UserAgent:       r.UserAgent,
		ClientVersion:   r.ClientVersion,
		RequestId:       r.RequestId,
		Title:           r.Title,
		Content:         r.Content,
		Excerpt:         r.Excerpt,
		Category:        r.Category,
		Tags:            r.Tags,
		Visibility:      r.Visibility,
		AllowComments:   r.AllowComments,
		PublishAt:       r.PublishAt,
		MetaTitle:       r.MetaTitle,
		MetaDescription: r.MetaDescription,
		SeoKeywords:     r.SeoKeywords,
		ImageUrls:       r.ImageUrls,
		AttachmentUrls:  r.AttachmentUrls,
		CustomFields:    r.CustomFields,
		ExternalId:      r.ExternalId,
	}
}

// _CreateUserGinRequest provides gin binding tags for CreateUserRequest
type _CreateUserGinRequest struct {
	Username            string            `json:"username" binding:"required,min=3,max=50,alphanum"`
	Email               string            `json:"email" binding:"required,email"`
	Password            string            `json:"password" binding:"required,min=8,max=128"`
	FullName            string            `json:"full_name" binding:"min=2,max=100"`
	Phone               string            `json:"phone" binding:"len=11,numeric"`
	Age                 int32             `json:"age" binding:"min=13,max=120"`
	Gender              string            `json:"gender" binding:"oneof=male female other"`
	Bio                 string            `json:"bio" binding:"max=500"`
	Address             *Address          `json:"address"`
	Hobbies             []string          `json:"hobbies" binding:"min=1,max=10"`
	Languages           []string          `json:"languages" binding:"max=20"`
	SocialLinks         map[string]string `json:"social_links"`
	Preferences         map[string]string `json:"preferences"`
	Settings            *UserSettings     `json:"settings"`
	AgreeTerms          bool              `json:"agree_terms" binding:"required,eq=true"`
	SubscribeNewsletter bool              `json:"subscribe_newsletter"`
	ReferralCode        string            `json:"referral_code" xml:"referral_format"`
	Tags                []string          `json:"tags" xml:"max_length:20"`
}

// convertCreateUserGinRequest converts from gin request struct to protobuf struct
func (r *_CreateUserGinRequest) toCreateUserRequest() *CreateUserRequest {
	return &CreateUserRequest{
		Username:            r.Username,
		Email:               r.Email,
		Password:            r.Password,
		FullName:            r.FullName,
		Phone:               r.Phone,
		Age:                 r.Age,
		Gender:              r.Gender,
		Bio:                 r.Bio,
		Address:             r.Address,
		Hobbies:             r.Hobbies,
		Languages:           r.Languages,
		SocialLinks:         r.SocialLinks,
		Preferences:         r.Preferences,
		Settings:            r.Settings,
		AgreeTerms:          r.AgreeTerms,
		SubscribeNewsletter: r.SubscribeNewsletter,
		ReferralCode:        r.ReferralCode,
		Tags:                r.Tags,
	}
}

// _DeleteUserGinRequest provides gin binding tags for DeleteUserRequest
type _DeleteUserGinRequest struct {
	UserId         string `json:"user_id" uri:"user_id" binding:"required,uuid"`
	HardDelete     bool   `json:"hard_delete" form:"hard_delete"`
	DeleteReason   string `json:"delete_reason" form:"reason" binding:"max=500"`
	TransferData   bool   `json:"transfer_data" form:"transfer_data"`
	TransferToUser string `json:"transfer_to_user" form:"transfer_to" binding:"uuid"`
	Confirmation   string `json:"confirmation" header:"X-Confirm-Delete" binding:"required,eq=DELETE"`
	Authorization  string `json:"authorization" header:"Authorization" binding:"required"`
	AdminToken     string `json:"admin_token" header:"X-Admin-Token"`
}

// convertDeleteUserGinRequest converts from gin request struct to protobuf struct
func (r *_DeleteUserGinRequest) toDeleteUserRequest() *DeleteUserRequest {
	return &DeleteUserRequest{
		UserId:         r.UserId,
		HardDelete:     r.HardDelete,
		DeleteReason:   r.DeleteReason,
		TransferData:   r.TransferData,
		TransferToUser: r.TransferToUser,
		Confirmation:   r.Confirmation,
		Authorization:  r.Authorization,
		AdminToken:     r.AdminToken,
	}
}

// _GetPostCommentsGinRequest provides gin binding tags for GetPostCommentsRequest
type _GetPostCommentsGinRequest struct {
	UserId         string `json:"user_id" uri:"user_id" binding:"required,uuid"`
	PostId         string `json:"post_id" uri:"post_id" binding:"required,uuid"`
	Page           int32  `json:"page" form:"page" binding:"min=1"`
	PerPage        int32  `json:"per_page" form:"per_page" binding:"min=1,max=100"`
	Sort           string `json:"sort" form:"sort" binding:"oneof=created_at updated_at likes replies"`
	Order          string `json:"order" form:"order" binding:"oneof=asc desc"`
	Status         string `json:"status" form:"status" binding:"oneof=all published hidden deleted"`
	IncludeReplies bool   `json:"include_replies" form:"include_replies"`
	IncludeHidden  bool   `json:"include_hidden" form:"include_hidden"`
	Since          string `json:"since" form:"since" binding:"datetime=2006-01-02T15:04:05Z07:00"`
	Until          string `json:"until" form:"until" binding:"datetime=2006-01-02T15:04:05Z07:00"`
	UserContext    string `json:"user_context" header:"X-User-Context"`
	ClientTimezone string `json:"client_timezone" header:"X-Client-Timezone"`
}

// convertGetPostCommentsGinRequest converts from gin request struct to protobuf struct
func (r *_GetPostCommentsGinRequest) toGetPostCommentsRequest() *GetPostCommentsRequest {
	return &GetPostCommentsRequest{
		UserId:         r.UserId,
		PostId:         r.PostId,
		Page:           r.Page,
		PerPage:        r.PerPage,
		Sort:           r.Sort,
		Order:          r.Order,
		Status:         r.Status,
		IncludeReplies: r.IncludeReplies,
		IncludeHidden:  r.IncludeHidden,
		Since:          r.Since,
		Until:          r.Until,
		UserContext:    r.UserContext,
		ClientTimezone: r.ClientTimezone,
	}
}

// _GetUserGinRequest provides gin binding tags for GetUserRequest
type _GetUserGinRequest struct {
	UserId         string   `json:"user_id" uri:"user_id" binding:"required,uuid"`
	Fields         []string `json:"fields" form:"fields"`
	IncludeProfile bool     `json:"include_profile" form:"include_profile"`
	IncludePosts   bool     `json:"include_posts" form:"include_posts"`
}

// convertGetUserGinRequest converts from gin request struct to protobuf struct
func (r *_GetUserGinRequest) toGetUserRequest() *GetUserRequest {
	return &GetUserRequest{
		UserId:         r.UserId,
		Fields:         r.Fields,
		IncludeProfile: r.IncludeProfile,
		IncludePosts:   r.IncludePosts,
	}
}

// _GetUserProfileGinRequest provides gin binding tags for GetUserProfileRequest
type _GetUserProfileGinRequest struct {
	UserId           string   `json:"user_id" uri:"user_id" binding:"required,uuid"`
	Sections         []string `json:"sections" form:"sections"`
	IncludeStats     bool     `json:"include_stats" form:"include_stats"`
	IncludePosts     bool     `json:"include_posts" form:"include_posts"`
	IncludeFollowers bool     `json:"include_followers" form:"include_followers"`
	ViewerContext    string   `json:"viewer_context" form:"context" binding:"oneof=public friend follower self"`
	ViewerId         string   `json:"viewer_id" header:"X-Viewer-ID"`
	AccessToken      string   `json:"access_token" header:"X-Access-Token"`
}

// convertGetUserProfileGinRequest converts from gin request struct to protobuf struct
func (r *_GetUserProfileGinRequest) toGetUserProfileRequest() *GetUserProfileRequest {
	return &GetUserProfileRequest{
		UserId:           r.UserId,
		Sections:         r.Sections,
		IncludeStats:     r.IncludeStats,
		IncludePosts:     r.IncludePosts,
		IncludeFollowers: r.IncludeFollowers,
		ViewerContext:    r.ViewerContext,
		ViewerId:         r.ViewerId,
		AccessToken:      r.AccessToken,
	}
}

// _ListUsersGinRequest provides gin binding tags for ListUsersRequest
type _ListUsersGinRequest struct {
	Page           int32    `json:"page" form:"page" binding:"min=1"`
	PageSize       int32    `json:"page_size" form:"page_size" binding:"min=1,max=100"`
	SortBy         string   `json:"sort_by" form:"sort_by" binding:"oneof=id name email created_at"`
	SortOrder      string   `json:"sort_order" form:"sort_order" binding:"oneof=asc desc"`
	Status         []string `json:"status" form:"status"`
	Roles          []string `json:"roles" form:"roles"`
	IncludeDeleted bool     `json:"include_deleted" form:"include_deleted"`
	IncludeStats   bool     `json:"include_stats" form:"include_stats"`
	CreatedAfter   string   `json:"created_after" form:"created_after" binding:"datetime=2006-01-02"`
	CreatedBefore  string   `json:"created_before" form:"created_before" binding:"datetime=2006-01-02"`
}

// convertListUsersGinRequest converts from gin request struct to protobuf struct
func (r *_ListUsersGinRequest) toListUsersRequest() *ListUsersRequest {
	return &ListUsersRequest{
		Page:           r.Page,
		PageSize:       r.PageSize,
		SortBy:         r.SortBy,
		SortOrder:      r.SortOrder,
		Status:         r.Status,
		Roles:          r.Roles,
		IncludeDeleted: r.IncludeDeleted,
		IncludeStats:   r.IncludeStats,
		CreatedAfter:   r.CreatedAfter,
		CreatedBefore:  r.CreatedBefore,
	}
}

// _PatchUserGinRequest provides gin binding tags for PatchUserRequest
type _PatchUserGinRequest struct {
	UserId            string            `json:"user_id" uri:"user_id" binding:"required,uuid"`
	IfMatch           string            `json:"if_match" header:"If-Match"`
	IfUnmodifiedSince string            `json:"if_unmodified_since" header:"If-Unmodified-Since"`
	Authorization     string            `json:"authorization" header:"Authorization" binding:"required"`
	PatchSource       string            `json:"patch_source" header:"X-Patch-Source"`
	Username          string            `json:"username" binding:"min=3,max=50"`
	Email             string            `json:"email" binding:"email"`
	FullName          string            `json:"full_name" binding:"min=2,max=100"`
	Phone             string            `json:"phone" binding:"len=11,numeric"`
	Bio               string            `json:"bio" binding:"max=1000"`
	Status            string            `json:"status" binding:"oneof=active inactive suspended"`
	ProfilePatches    map[string]string `json:"profile_patches"`
	SettingsPatches   map[string]string `json:"settings_patches"`
	AddressPatches    map[string]string `json:"address_patches"`
	AddRoles          []string          `json:"add_roles"`
	RemoveRoles       []string          `json:"remove_roles"`
	AddTags           []string          `json:"add_tags"`
	RemoveTags        []string          `json:"remove_tags"`
	PatchReason       string            `json:"patch_reason" binding:"max=200"`
	PatchMetadata     map[string]string `json:"patch_metadata"`
}

// convertPatchUserGinRequest converts from gin request struct to protobuf struct
func (r *_PatchUserGinRequest) toPatchUserRequest() *PatchUserRequest {
	return &PatchUserRequest{
		UserId:            r.UserId,
		IfMatch:           r.IfMatch,
		IfUnmodifiedSince: r.IfUnmodifiedSince,
		Authorization:     r.Authorization,
		PatchSource:       r.PatchSource,
		Username:          r.Username,
		Email:             r.Email,
		FullName:          r.FullName,
		Phone:             r.Phone,
		Bio:               r.Bio,
		Status:            r.Status,
		ProfilePatches:    r.ProfilePatches,
		SettingsPatches:   r.SettingsPatches,
		AddressPatches:    r.AddressPatches,
		AddRoles:          r.AddRoles,
		RemoveRoles:       r.RemoveRoles,
		AddTags:           r.AddTags,
		RemoveTags:        r.RemoveTags,
		PatchReason:       r.PatchReason,
		PatchMetadata:     r.PatchMetadata,
	}
}

// _RegisterUserGinRequest provides gin binding tags for RegisterUserRequest
type _RegisterUserGinRequest struct {
	Username            string   `json:"username" form:"username" binding:"required,min=3,max=30,alphanum"`
	Email               string   `json:"email" form:"email" binding:"required,email"`
	Password            string   `json:"password" form:"password" binding:"required,min=8"`
	ConfirmPassword     string   `json:"confirm_password" form:"confirm_password" binding:"required,eqfield=Password"`
	FirstName           string   `json:"first_name" form:"first_name" binding:"required,min=2,max=50"`
	LastName            string   `json:"last_name" form:"last_name" binding:"required,min=2,max=50"`
	BirthDate           string   `json:"birth_date" form:"birth_date" binding:"required,datetime=2006-01-02"`
	Phone               string   `json:"phone" form:"phone" binding:"required,len=11,numeric"`
	Gender              string   `json:"gender" form:"gender" binding:"oneof=male female other prefer_not_to_say"`
	Country             string   `json:"country" form:"country" binding:"required,min=2,max=2"`
	Timezone            string   `json:"timezone" form:"timezone" binding:"required"`
	Interests           []string `json:"interests" form:"interests"`
	Skills              []string `json:"skills" form:"skills"`
	NewsletterFrequency string   `json:"newsletter_frequency" form:"newsletter" binding:"oneof=never daily weekly monthly"`
	MarketingEmails     bool     `json:"marketing_emails" form:"marketing_emails"`
	CaptchaResponse     string   `json:"captcha_response" form:"captcha" binding:"required,len=6"`
	InviteCode          string   `json:"invite_code" form:"invite_code"`
	UtmSource           string   `json:"utm_source" form:"utm_source"`
	UtmMedium           string   `json:"utm_medium" form:"utm_medium"`
	UtmCampaign         string   `json:"utm_campaign" form:"utm_campaign"`
	ReferrerUrl         string   `json:"referrer_url" form:"referrer"`
}

// convertRegisterUserGinRequest converts from gin request struct to protobuf struct
func (r *_RegisterUserGinRequest) toRegisterUserRequest() *RegisterUserRequest {
	return &RegisterUserRequest{
		Username:            r.Username,
		Email:               r.Email,
		Password:            r.Password,
		ConfirmPassword:     r.ConfirmPassword,
		FirstName:           r.FirstName,
		LastName:            r.LastName,
		BirthDate:           r.BirthDate,
		Phone:               r.Phone,
		Gender:              r.Gender,
		Country:             r.Country,
		Timezone:            r.Timezone,
		Interests:           r.Interests,
		Skills:              r.Skills,
		NewsletterFrequency: r.NewsletterFrequency,
		MarketingEmails:     r.MarketingEmails,
		CaptchaResponse:     r.CaptchaResponse,
		InviteCode:          r.InviteCode,
		UtmSource:           r.UtmSource,
		UtmMedium:           r.UtmMedium,
		UtmCampaign:         r.UtmCampaign,
		ReferrerUrl:         r.ReferrerUrl,
	}
}

// _SearchUsersGinRequest provides gin binding tags for SearchUsersRequest
type _SearchUsersGinRequest struct {
	Query        string   `json:"query" form:"q" binding:"required,min=2,max=100"`
	SearchFields []string `json:"search_fields" form:"search_fields"`
	Limit        int32    `json:"limit" form:"limit" binding:"min=1,max=50"`
	ClientId     string   `json:"client_id" header:"X-Client-ID" binding:"required"`
	RequestId    string   `json:"request_id" header:"X-Request-ID"`
	UserAgent    string   `json:"user_agent" header:"User-Agent"`
	ApiKey       string   `json:"api_key" header:"X-API-Key" binding:"required,min=32,max=64"`
	Latitude     float64  `json:"latitude" form:"lat" binding:"min=-90,max=90"`
	Longitude    float64  `json:"longitude" form:"lng" binding:"min=-180,max=180"`
	RadiusKm     int32    `json:"radius_km" form:"radius" binding:"min=1,max=1000"`
	MinAge       int32    `json:"min_age" form:"min_age" binding:"min=0,max=150"`
	MaxAge       int32    `json:"max_age" form:"max_age" binding:"min=0,max=150"`
	Country      string   `json:"country" form:"country"`
	City         string   `json:"city" form:"city"`
}

// convertSearchUsersGinRequest converts from gin request struct to protobuf struct
func (r *_SearchUsersGinRequest) toSearchUsersRequest() *SearchUsersRequest {
	return &SearchUsersRequest{
		Query:        r.Query,
		SearchFields: r.SearchFields,
		Limit:        r.Limit,
		ClientId:     r.ClientId,
		RequestId:    r.RequestId,
		UserAgent:    r.UserAgent,
		ApiKey:       r.ApiKey,
		Latitude:     r.Latitude,
		Longitude:    r.Longitude,
		RadiusKm:     r.RadiusKm,
		MinAge:       r.MinAge,
		MaxAge:       r.MaxAge,
		Country:      r.Country,
		City:         r.City,
	}
}

// _UpdateProfileGinRequest provides gin binding tags for UpdateProfileRequest
type _UpdateProfileGinRequest struct {
	UserId  string       `json:"user_id" uri:"user_id" binding:"required,uuid"`
	Profile *UserProfile `json:"profile"`
}

// convertUpdateProfileGinRequest converts from gin request struct to protobuf struct
func (r *_UpdateProfileGinRequest) toUpdateProfileRequest() *UpdateProfileRequest {
	return &UpdateProfileRequest{
		UserId:  r.UserId,
		Profile: r.Profile,
	}
}

// _UpdateUserGinRequest provides gin binding tags for UpdateUserRequest
type _UpdateUserGinRequest struct {
	UserId           string            `json:"user_id" uri:"user_id" binding:"required,uuid"`
	SendNotification bool              `json:"send_notification" form:"send_notification"`
	UpdateReason     string            `json:"update_reason" form:"reason"`
	IfMatch          string            `json:"if_match" header:"If-Match"`
	Authorization    string            `json:"authorization" header:"Authorization" binding:"required"`
	Username         string            `json:"username" binding:"required,min=3,max=50"`
	Email            string            `json:"email" binding:"required,email"`
	FullName         string            `json:"full_name" binding:"required,min=2,max=100"`
	Phone            string            `json:"phone" binding:"len=11,numeric"`
	Age              int32             `json:"age" binding:"min=13,max=120"`
	Bio              string            `json:"bio" binding:"max=1000"`
	Status           string            `json:"status" binding:"required,oneof=active inactive suspended banned"`
	Roles            []string          `json:"roles" binding:"min=1"`
	Address          *Address          `json:"address"`
	SocialLinks      map[string]string `json:"social_links"`
	Settings         *UserSettings     `json:"settings"`
	UpdatedAt        string            `json:"updated_at" binding:"required,datetime=2006-01-02T15:04:05Z07:00"`
	Version          int32             `json:"version" binding:"required,min=1"`
}

// convertUpdateUserGinRequest converts from gin request struct to protobuf struct
func (r *_UpdateUserGinRequest) toUpdateUserRequest() *UpdateUserRequest {
	return &UpdateUserRequest{
		UserId:           r.UserId,
		SendNotification: r.SendNotification,
		UpdateReason:     r.UpdateReason,
		IfMatch:          r.IfMatch,
		Authorization:    r.Authorization,
		Username:         r.Username,
		Email:            r.Email,
		FullName:         r.FullName,
		Phone:            r.Phone,
		Age:              r.Age,
		Bio:              r.Bio,
		Status:           r.Status,
		Roles:            r.Roles,
		Address:          r.Address,
		SocialLinks:      r.SocialLinks,
		Settings:         r.Settings,
		UpdatedAt:        r.UpdatedAt,
		Version:          r.Version,
	}
}
